-- prism create tables and utility tables
--
-- SEQUENCES


CREATE SEQUENCE irp.irp_chameleon_seq INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE irp.irp_contacts_seq START WITH 410756 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE irp.irp_lookups_seq INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

--
--------------------------------------------------------
--  DDL for Sequence ERROR_LINES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "UTILITY"."ERROR_LINES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 215 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence ERRORS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "UTILITY"."ERRORS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 128 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence LOG_STACK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "UTILITY"."LOG_STACK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;

create sequence irp.irp_notes_seq;
--------------------------------------------------------
--  DDL for Table APP_LOG
--------------------------------------------------------

  CREATE TABLE "UTILITY"."APP_LOG" 
   (	"ID" NUMBER, 
	"UNIT" VARCHAR2(65 CHAR), 
	"LINE" NUMBER, 
	"USERNAME" VARCHAR2(128 CHAR), 
	"STIME" TIMESTAMP (6) DEFAULT current_timestamp, 
	"ETIME" TIMESTAMP (6), 
	"PARMS" CLOB, 
	"RESULTS" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_SMALL" 
 LOB ("PARMS") STORE AS SECUREFILE (
  TABLESPACE "PIRP_DATA_SMALL" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESULTS") STORE AS SECUREFILE (
  TABLESPACE "PIRP_DATA_SMALL" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DEBUG
--------------------------------------------------------

  CREATE TABLE "UTILITY"."DEBUG" 
   (	"UNIT" VARCHAR2(35 CHAR) DEFAULT '*', 
	"USERNAME" VARCHAR2(128 CHAR) DEFAULT '*'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_SMALL" ;
--------------------------------------------------------
--  DDL for Table ERROR_LINES
--------------------------------------------------------

  CREATE TABLE "UTILITY"."ERROR_LINES" 
   (	"ID" NUMBER, 
	"ERRORS_ID" NUMBER, 
	"DYNAMIC_DEPT" NUMBER, 
	"OWNER" VARCHAR2(128 BYTE), 
	"SUBPRG_NAME" VARCHAR2(128 BYTE), 
	"ERROR_MSG" VARCHAR2(256 BYTE), 
	"ERROR_NUMBER" NUMBER, 
	"PLSQL_LINE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_SMALL" ;

   COMMENT ON COLUMN "UTILITY"."ERROR_LINES"."OWNER" IS 'the owner of the pl/sql unit that was called.';
   COMMENT ON COLUMN "UTILITY"."ERROR_LINES"."SUBPRG_NAME" IS 'the function,procedure that was called in a package. we are leaving this nullable for now. there is the possibility that a procedure,function,trigger can be called and will not be part of a package.';
--------------------------------------------------------
--  DDL for Table ERRORS
--------------------------------------------------------

  CREATE TABLE "UTILITY"."ERRORS" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(128 BYTE), 
	"IP_ADDRESS" VARCHAR2(15 BYTE), 
	"TIMESTAMP#" TIMESTAMP (6) WITH TIME ZONE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_SMALL" ;

   COMMENT ON COLUMN "UTILITY"."ERRORS"."ID" IS 'Primary key for the errors table.';
   COMMENT ON COLUMN "UTILITY"."ERRORS"."USERNAME" IS 'The user that executed the code.';
   COMMENT ON COLUMN "UTILITY"."ERRORS"."IP_ADDRESS" IS 'the ip address that the code was executed from.';
   COMMENT ON COLUMN "UTILITY"."ERRORS"."TIMESTAMP#" IS 'the timestamp when the code was executed.';
--------------------------------------------------------
--  DDL for Index app_log_uidx1
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTILITY"."app_log_uidx1" ON "UTILITY"."APP_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_INDEX_SMALL" ;
--------------------------------------------------------
--  DDL for Index ERROR_LINES__IDX
--------------------------------------------------------

  CREATE INDEX "UTILITY"."ERROR_LINES__IDX" ON "UTILITY"."ERROR_LINES" ("ERRORS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_INDEX_SMALL" ;
--------------------------------------------------------
--  DDL for Index ERROR_LINES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTILITY"."ERROR_LINES_PK" ON "UTILITY"."ERROR_LINES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_INDEX_SMALL" ;
--------------------------------------------------------
--  DDL for Index ERRORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UTILITY"."ERRORS_PK" ON "UTILITY"."ERRORS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_INDEX_SMALL" ;
--------------------------------------------------------
--  Constraints for Table APP_LOG
--------------------------------------------------------

  ALTER TABLE "UTILITY"."APP_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_INDEX_SMALL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEBUG
--------------------------------------------------------

  ALTER TABLE "UTILITY"."DEBUG" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "UTILITY"."DEBUG" MODIFY ("UNIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ERROR_LINES
--------------------------------------------------------

  ALTER TABLE "UTILITY"."ERROR_LINES" ADD CONSTRAINT "ERROR_LINES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_INDEX_SMALL"  ENABLE;
  ALTER TABLE "UTILITY"."ERROR_LINES" MODIFY ("DYNAMIC_DEPT" NOT NULL ENABLE);
  ALTER TABLE "UTILITY"."ERROR_LINES" MODIFY ("ERRORS_ID" NOT NULL ENABLE);
  ALTER TABLE "UTILITY"."ERROR_LINES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ERRORS
--------------------------------------------------------

  ALTER TABLE "UTILITY"."ERRORS" ADD CONSTRAINT "ERRORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_INDEX_SMALL"  ENABLE;
  ALTER TABLE "UTILITY"."ERRORS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "UTILITY"."ERRORS" MODIFY ("ID" NOT NULL ENABLE);
  
  -------------------------------------------------------
  -- IRP_APPLICANTS CHANGES
  -------------------------------------------------------
  ALTER TABLE IRP.IRP_APPLICANTS ADD IRP_APP_CHAMILEON_SCORE NUMBER;
  
  CREATE TABLE "IRP"."IRP_CHAMELEONS" 
   (	"IRP_CHA_ID" NUMBER, 
	"IRP_CHA_IRPNBR" NUMBER(6,0), 
	"IRP_CHA_USDOTNBR" VARCHAR2(12 BYTE), 
	"IRP_CHA_VIN" VARCHAR2(19 BYTE), 
	"IRP_CHA_SCORE" NUMBER, 
	"IRP_CHA_ATTRIBUTE" VARCHAR2(25 BYTE), 
	"IRP_CHA_TITLENBR" VARCHAR2(8 CHAR), 
	"IRP_CHA_OVERRIDE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM" ;
--------------------------------------------------------
--  DDL for Index IRP_CHAMELEON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IRP"."IRP_CHAMELEON_PK" ON "IRP"."IRP_CHAMELEONS" ("IRP_CHA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM" ;
--------------------------------------------------------
--  Constraints for Table IRP_CHAMELEONS
--------------------------------------------------------

  ALTER TABLE "IRP"."IRP_CHAMELEONS" ADD CONSTRAINT "IRP_CHAMELEON_PK" PRIMARY KEY ("IRP_CHA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM"  ENABLE;
  ALTER TABLE "IRP"."IRP_CHAMELEONS" MODIFY ("IRP_CHA_ATTRIBUTE" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CHAMELEONS" MODIFY ("IRP_CHA_SCORE" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CHAMELEONS" MODIFY ("IRP_CHA_USDOTNBR" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CHAMELEONS" MODIFY ("IRP_CHA_IRPNBR" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CHAMELEONS" MODIFY ("IRP_CHA_ID" NOT NULL ENABLE);

  
CREATE TABLE IRP.IRP_COMMON_NAMES 
    ( 
     NAME           VARCHAR2 (35 BYTE)  NOT NULL , 
     NAME_VARIATION VARCHAR2 (35 BYTE) , 
     PROBABILITY    NUMBER 
    ) 
        TABLESPACE PIRP_DATA_MEDIUM 
        LOGGING
;


--------------------------------------------------------
--  DDL for Table IRP_CONTACTS
--------------------------------------------------------

  CREATE TABLE "IRP"."IRP_CONTACTS" 
   (	"IRP_CON_ID" NUMBER, 
	"IRP_CON_IRPNBR" NUMBER(6,0), 
	"IRP_CON_FNAME" VARCHAR2(35 CHAR), 
	"IRP_CON_MNAME" VARCHAR2(35 BYTE), 
	"IRP_CON_LNAME" VARCHAR2(35 BYTE), 
	"IRP_CON_PHONE" VARCHAR2(14 CHAR), 
	"IRP_CON_EMAIL" VARCHAR2(100 CHAR), 
	"IRP_CON_PRIMARY" VARCHAR2(1 CHAR), 
	"IRP_CON_MOBILE" VARCHAR2(10 CHAR), 
	"IRP_CON_SUFFIX" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM" ;
--------------------------------------------------------
--  DDL for Index IRP_CONTACTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IRP"."IRP_CONTACTS_PK" ON "IRP"."IRP_CONTACTS" ("IRP_CON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM" ;
--------------------------------------------------------
--  DDL for Index IRP_CONTACTS_CHK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IRP"."IRP_CONTACTS_CHK" ON "IRP"."IRP_CONTACTS" ("IRP_CON_IRPNBR", "IRP_CON_FNAME", "IRP_CON_LNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM" ;
--------------------------------------------------------
--  Constraints for Table IRP_CONTACTS
--------------------------------------------------------

  ALTER TABLE "IRP"."IRP_CONTACTS" ADD CONSTRAINT "IRP_CONTACTS_PK" PRIMARY KEY ("IRP_CON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM"  ENABLE;
  ALTER TABLE "IRP"."IRP_CONTACTS" MODIFY ("IRP_CON_PRIMARY" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CONTACTS" MODIFY ("IRP_CON_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CONTACTS" MODIFY ("IRP_CON_PHONE" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CONTACTS" MODIFY ("IRP_CON_LNAME" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CONTACTS" MODIFY ("IRP_CON_FNAME" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CONTACTS" MODIFY ("IRP_CON_IRPNBR" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_CONTACTS" MODIFY ("IRP_CON_ID" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table IRP_LOOKUPS
--------------------------------------------------------

  CREATE TABLE "IRP"."IRP_LOOKUPS" 
   (	"IRP_LOK_ID" NUMBER, 
	"IRP_LOK_TYPE" VARCHAR2(25 BYTE), 
	"IRP_LOK_VALUE" VARCHAR2(25 BYTE), 
	"IRP_LOK_DESCRIPTION" VARCHAR2(4000 BYTE) DEFAULT 'enter value for description'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0019392
--------------------------------------------------------

  CREATE UNIQUE INDEX "IRP"."SYS_C0019392" ON "IRP"."IRP_LOOKUPS" ("IRP_LOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM" ;
--------------------------------------------------------
--  Constraints for Table IRP_LOOKUPS
--------------------------------------------------------

  ALTER TABLE "IRP"."IRP_LOOKUPS" MODIFY ("IRP_LOK_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_LOOKUPS" ADD PRIMARY KEY ("IRP_LOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM"  ENABLE;
  ALTER TABLE "IRP"."IRP_LOOKUPS" MODIFY ("IRP_LOK_VALUE" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_LOOKUPS" MODIFY ("IRP_LOK_TYPE" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table IRP_NOTES
--------------------------------------------------------

  CREATE TABLE "IRP"."IRP_NOTES" 
   (	"IRP_NOT_ID" NUMBER(*,0), 
	"IRP_NOT_CREATED" DATE, 
	"IRP_NOT_NOTE" CLOB, 
	"IRP_NOT_CEM_ID" NUMBER, 
	"IRP_NOT_AUDINFO" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM" 
 LOB ("IRP_NOT_NOTE") STORE AS SECUREFILE (
  TABLESPACE "PIRP_DATA_MEDIUM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index IRP_NOTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IRP"."IRP_NOTES_PK" ON "IRP"."IRP_NOTES" ("IRP_NOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM" ;
--------------------------------------------------------
--  Constraints for Table IRP_NOTES
--------------------------------------------------------

  ALTER TABLE "IRP"."IRP_NOTES" ADD CONSTRAINT "IRP_NOTES_PK" PRIMARY KEY ("IRP_NOT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIRP_DATA_MEDIUM"  ENABLE;
  ALTER TABLE "IRP"."IRP_NOTES" MODIFY ("IRP_NOT_CEM_ID" NOT NULL ENABLE);
  ALTER TABLE "IRP"."IRP_NOTES" MODIFY ("IRP_NOT_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for View IRP_APPLICANTSREG_VW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IRP"."IRP_APPLICANTSREG_VW" ("IRP_APP_IRPNBR", "IRP_APP_COMPANY", "IRP_APP_ADDSTREET", "IRP_APP_ADDLINE2", "IRP_APP_ADDCITY", "IRP_APP_ADDCOUNTY", "IRP_APP_ADDSTATE", "IRP_APP_ADDZIP", "IRP_APP_CONLNAME", "IRP_APP_CONFAX", "IRP_APP_PRTSD", "IRP_APP_REMARKS", "IRP_APP_STATUS", "IRP_APP_USERID", "IRP_APP_ACTIVITYDATE", "IRP_APP_USDOTNO", "IRP_APP_IFTA", "IRP_APP_CONPHONE", "IRP_APP_CONEMAIL", "IRP_APP_REGONLY", "IRP_APP_PRISMCHK", "IRP_APP_PRISMSTATUS", "IRP_APP_TARGET", "IRP_PLC_USDOTNO", "IRP_PLC_TIN", "IRP_PLC_COMPANY", "IRP_PLC_CARRIERSTAT", "IRP_PLC_MCSIPFLG", "IRP_PLC_ENTITYTYPE", "IRP_PLC_MCSIPSTEP", "IRP_PLC_MCS150LSTUPD", "IRP_MCS_DENYREG", "IRP_MCS_IRPSTATUS", "IRP_APP_CHAMELEON_SCORE") AS 
  SELECT A.IRP_APP_IRPNBR ,
    A.IRP_APP_COMPANY     ,
    A.IRP_APP_ADDSTREET   ,
    A.IRP_APP_ADDLINE2    ,
    A.IRP_APP_ADDCITY     ,
    A.IRP_APP_ADDCOUNTY   ,
    A.IRP_APP_ADDSTATE    ,
    A.IRP_APP_ADDZIP      ,
    A.IRP_APP_CONLNAME    ,
    A.IRP_APP_CONFAX      ,
    A.IRP_APP_PRTSD       ,
    A.IRP_APP_REMARKS     ,
    A.IRP_APP_STATUS      ,
    A.IRP_APP_USERID      ,
    A.IRP_APP_ACTIVITYDATE,
    A.IRP_APP_USDOTNO     ,
    A.IRP_APP_IFTA        ,
    A.IRP_APP_CONPHONE    ,
    A.IRP_APP_CONEMAIL    ,
    A.IRP_APP_REGONLY     ,
    A.IRP_APP_PRISMCHK    ,
    A.IRP_APP_PRISMSTATUS ,
    A.IRP_APP_TARGET      ,
    P.IRP_PLC_USDOTNO     ,
    P.IRP_PLC_TIN         ,
    P.IRP_PLC_COMPANY     ,
    P.IRP_PLC_CARRIERSTAT ,
    P.IRP_PLC_MCSIPFLG    ,
    P.IRP_PLC_ENTITYTYPE  ,
    P.IRP_PLC_MCSIPSTEP   ,
    P.IRP_PLC_MCS150LSTUPD,
    M.IRP_MCS_DENYREG     ,
    M.IRP_MCS_IRPSTATUS	  ,
    A.IRP_APP_CHAMELEON_SCORE
  FROM IRP_APPLICANTS A,
    IRP_PRSMLCLCENSUS P,
    IRP_PRISMMCSIP M
  WHERE P.IRP_PLC_USDOTNO(+) = LPAD (A.IRP_APP_USDOTNO, 7, '0')
    AND M.IRP_MCS_STEP(+)    = P.IRP_PLC_MCSIPSTEP
;


ALTER TABLE irp.irp_applicants MODIFY ( irp_app_company VARCHAR2(55 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_fein VARCHAR2(9 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_addstreet VARCHAR2(40 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_addline2 VARCHAR2(40 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_addcity VARCHAR2(25 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_addcounty VARCHAR2(15 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_addstate VARCHAR2(2 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_addzip VARCHAR2(10 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_conlname VARCHAR2(35 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_confax VARCHAR2(12 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_prtsd VARCHAR2(1 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_remarks VARCHAR2(80 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_status VARCHAR2(1 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_userid VARCHAR2(10 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_usdotno VARCHAR2(12 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_ifta VARCHAR2(9 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_conphone VARCHAR2(14 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_conemail VARCHAR2(250 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_regonly VARCHAR2(1 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_prismstatus VARCHAR2(1 CHAR) );

ALTER TABLE irp.irp_applicants MODIFY ( irp_app_target VARCHAR2(1 CHAR) );

ALTER TABLE irp.irp_applicants ADD (
    irp_app_chamillion_score   NUMBER DEFAULT 0 NOT NULL
);

ALTER TABLE IRP.IRP_APPLICANTS DROP CONSTRAINT IRP_APP_IRPNBR_PK CASCADE DROP INDEX 
;

CREATE UNIQUE INDEX IRP.IRP_APP_IRPNBR_PK ON IRP.IRP_APPLICANTS 
    ( 
     IRP_APP_IRPNBR ASC 
    ) 
    TABLESPACE PIRP_INDEX_SMALL 
    
    LOGGING 
;

ALTER TABLE IRP.IRP_APPLICANTS 
    ADD CONSTRAINT IRP_APP_IRPNBR_PK PRIMARY KEY ( 
    IRP_APP_IRPNBR  
    ) 
    USING INDEX IRP.IRP_APP_IRPNBR_PK ;


--
-- GRANTS
-- 
-- grants that irp needs.
GRANT REFERENCES, SELECT ON "UTILITY"."APP_LOG" TO IRP;
GRANT REFERENCES, SELECT ON "UTILITY"."DEBUG"  TO IRP;
GRANT REFERENCES, SELECT ON UTILITY.ERROR_LINES TO IRP;
GRANT REFERENCES, SELECT ON "UTILITY"."ERRORS" TO IRP;
GRANT REFERENCES, SELECT ON IRP.IRP_FLEETVEHICLE_VW TO IRP;

